### PR TITLE
OoyalaSkinSampleApp - Activity to dynamically add and play asset

### PR DESCRIPTION
**Pull request by skumar2905**

### CODE REVIEW

**Comment by brol1dev** [comment]
@skumar2905, would this new Activity be used by automation or how would you be using it? I think that using it manually (typing the embed code) would be slower since our embed codes are large.

**Comment by skumar2905** [comment]
@rcvrgs Yes, this Activity will be mainly used for Automation. But can also be used for manual testing  by using screen mirroring apps like Vysor with which we can copy/paste the embedCode and pcode.

**Review by akshaydch11 — APPROVED** [review]

**Comment by akshaydch11** [comment]
LGTM 
@rcvrgs Please merge if you are good

**Review by brol1dev — APPROVED** [review]
LGTM

**Pull request merged**
