### PR TITLE
[PLAYER-4730] Unable to build from android-sample-apps repo

### PR DESCRIPTION
**Pull request by orobles-ooyala**
- Added missing dependencies

### CODE REVIEW

**Review by SergeyBicarte — APPROVED** [review]

**Review by SergeyBicarte — CHANGES_REQUESTED** [review]
It seems broken for build with skin as module (instead of as library).
Looks like it's because native-skin  project does not updated with androidX and using old versions of support libraries.  I see errors in  numerous native-skin files , for example : native-skin\sdk\android\skin\src\main\java\com\ooyala\android\skin\view\ClosedCaptionsView.java generate 
error: package android.support.v7.widget does not exist

**Comment by orobles-ooyala** [comment]
@SergeyBicarte I have created PLAYER-4761 for that use case.

**Review by SergeyBicarte — APPROVED** [review]
LGTM

**Review by cacel — APPROVED** [review]
LGTM

**Pull request merged**
