### PR TITLE
Fullscreen event listening support for sample apps

### PR DESCRIPTION
**Pull request by akshaydch11**

### CODE REVIEW

**Comment by brol1dev** [comment]
Why don't we use the Activity as the Observer for the OoyalaSkinLayoutController? We already do that for the OoyalaPlayer, might as well do the same for OoyalaSkinLayoutController. Something like:

```
public void update(Observable observable, Object data) {
  if (observable instanceof OoyalaSkinLayoutController) {
    // skinLayoutController notifications
  } else if (observable instanceof OoyalaPlayer) {
    // player notifications
  }
}
```

You might have thought about it before, maybe you saw something wrong with it. What do you think?

**Comment by akshaydch11** [comment]
@rcvrgs I have changed it now. Before I was not using OoyalaNotification class. Now, observer for fullscreen is also using OoyalaNotification. And both observers are now handled in update method.

**Comment by brol1dev** [comment]
I just learned about the Java String's intern() method: http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/String.html#intern(), which kinda explains why comparing our Notification string constants, like `arg1 == OoyalaSkinLayoutController.FULLSCREEN_CHANGED_NOTIFICATION_NAME` works.

I always though that String comparison should always be like `arg1.equals(OoyalaSkinLayoutController.FULLSCREEN_CHANGED_NOTIFICATION_NAME)`, but now I know that if you use `==` for constants it will work too, and that's why it has always worked for us.

More about it here: https://en.wikipedia.org/wiki/String_interning

Just wanted to share :)

**Comment by brol1dev** [comment]
BTW, LGTM!

**Pull request merged**
