### PR TITLE
PLAYER-1959- Downloads Serialization

### PR DESCRIPTION
**Pull request by ipadilla4**
https://jira.corp.ooyala.com/browse/PLAYER-1959

### CODE REVIEW

**Review by brol1dev — CHANGES_REQUESTED** [review]
There are still things missing for this one. 
* In a real device you get an error in which you cannot create the folder in which the assets will live. Check how we ask for permission in the other Download Activity we have.
* Even if you complete to download there's no way to playback the downloaded asset. The only way right now would be to set the embed code in the existing player activity but that would be a step done before compiling the app each time. Can you add a click listener to all the assets in the list you build to start a player activity with the asset information to be played?
* The OPT information should be applied to individual assets independently. The current activity only lets you set one key and secret but it has to be the same account, can you change it so that you can supply key and secret per asset if OPT is required?

The app works good it's just that it needs more stuff so that we consider it completed.

Let's sync about this starting the week. Thanks @ipadilla4!

**Comment by ipadilla4** [comment]
Hi Eric, can you elaborate more on OPT point? I don't quite understand what do you mean. The other two points were already solved in my latest commit. Thanks @rcvrgs!

**Review by brol1dev — APPROVED** [review]
Great @ipadilla4  👍 I like how it looks.

About OPT we can decide to customize it in a separate PR. What I meant is that the `API_KEY`, `SECRET` and `ACCOUNT_ID` should be set per asset since right now they are used for all of the assets. In a real scenario a customer will not modify the key and secret per asset but it would help us internally to test so that we don't have to build the app with different key and secret that only works for a subset of the asset.

But we can talk about it later, the app is ok as it is right now. 

One thing I think you removed is the progress bar :( I think you had it, is there a reason why you removed it? It would be very practical for the user to know the progress of the download since we do show it iOS.

But I'm good with the PR as it is, so I'm approving.

**Comment by akshaydch11** [comment]
Looks great 👍 

It will be good to get progress bar somewhere on UI. One more change, we should add is pause button. 
When video starts downloading, we should show pause button. Clicking on it will pause the download that particular video.
If video is pause then show resume button, clicking on it will resume download.


@ipadilla4  Do you think it is easy to add above changes in this PR ? If it is short effort please go for it. If it is more effort we can sync with product guys if it needs to be added.

**Comment by akshaydch11** [comment]
As per discussion in stand up let create new story for pause/resume tickets.

**Pull request merged**
