### PR TITLE
[PBA-5680] Added commented dexOptions to OoyalaSkinSampleApp

### PR DESCRIPTION
**Pull request by brol1dev**
Uncomment jumboMode when you run into issues like: “Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index X into a non-jumbo instruction!”

### CODE REVIEW

**Comment by brol1dev** [comment]
Added a new commit that uncomments jumboMode for the apps that get the error. QA needs it to run automation tests successfully.

**Comment by brol1dev** [comment]
Note that this is being consistent when we have the SkinSDK in the app, we need to revisit our dependency tree.

**Review by jpfranco — APPROVED** [review]
LGTM

**Comment by brol1dev** [comment]
I will self merge so QA can test tonight

**Pull request merged**
