### PR TITLE
Revert "[REERT_PLAYER-2639] reverted code for programming screenshot"

### PR DESCRIPTION
**Pull request by AlinaVoronkovaEpam**
This reverts commit 9489d9e2a2c6146284f95951f1b6d524537a8344.

### CODE REVIEW

**Comment by brol1dev** [comment]
I think we already reverted it. Don't think we need this PR anymore.

**Comment by brol1dev** [comment]
@akshaydch11 please confirm and close if you agree.

**Review by brol1dev — COMMENTED** [review]
Added comments in the PR related to this one in our android-sdk. Review them first and I'll check this one after that one is ready/merged.

**Review by akshaydch11 — APPROVED** [review]

**Review by akshaydch11 — APPROVED** [review]

**Comment by akshaydch11** [comment]
Merging this now.

**Pull request merged**
