### PR TITLE
[PLAYER-2841] Android Heartbeat to SSAI: Sample App

### PR DESCRIPTION
**Pull request by orobles-ooyala**

### CODE REVIEW

**Review by brol1dev — COMMENTED** [review]
@orobles-ooyala, can we have a code review session to talk about this PR? Set a meeting and invite the people you think should be part of it.

Would prefer to talk about this one online.

**Comment by pilievOoyala** [comment]
LGTM. Does this need to go in for the march release?  Asking since it's a sample app and not core code.

**Comment by orobles-ooyala** [comment]
As soon as posible, please.

**Review by ipadilla4 — APPROVED** [review]
LGTM 👍

**Pull request merged**
