### PR TITLE
[PLAYER-2772] Possibility to save and extract downloaded stream info for offline video

### PR DESCRIPTION
**Pull request by IvanSakharovskii**

### CODE REVIEW

**Comment by brol1dev** [comment]
We can wait on this one until we make a new cut so that the SDK code is available. I'm good with it just waiting for an RC with the changes of the `UnbundledVideo` API.

**Review by brol1dev — APPROVED** [review]

**Comment by brol1dev** [comment]
I'm reviewing this PR again and there are a lot of not related changes in this PR. Why did you added some attributes in the XMLs?

**Comment by IvanSakharovskii** [comment]
@rcvrgs Removed code from XML files. And created different PR for them. We had the task for PIP support in android

**Comment by brol1dev** [comment]
I think this will get merged automatically when we merge candidate into dev after the release. We can safely close this one.

**Comment by brol1dev** [comment]
@IvanSakharovskii, @AlinaVoronkovaEpam, can you update this PR with the latest changes in `dev`? I think this PR might not be needed anymore.

**Comment by akshaydch11** [comment]
@IvanSakharovskii  @AlinaVoronkovaEpam  Do we still need this PR ?

**Pull request closed without merging**
