### PR TITLE
[PBA-4289] add DTO sample app to playback lab

### PR DESCRIPTION
**Pull request by Matthew-C**

### CODE REVIEW

**Comment by lental** [comment]
this won't run because I don't have updated ooyalaSDK jars.  after Android SDK code gets merged in and we do the dev push, I will be able to run the app and try it out

**Comment by Matthew-C** [comment]
I checked in the jar built from my local branch so it should run.

Matthew

**Comment by lental** [comment]
I don't doubt you, but i do want to run it myself.  If it's okay we'll get the android-sdk stuff through

**Comment by brol1dev** [comment]
Yep, also wanted to test it locally but I have a different OoyalaSDK.jar :( I'll try linking to my local Android sdk repo instead of using the one in vendor.

**Comment by Matthew-C** [comment]
raise this again after I updated OoyalaSDK.jar

**Comment by lental** [comment]
please rename the app, and change the application package name in build.gradle, android manfiest, and any strings.xml string or in the app (clashes with exoplayersampleapp)

The font doesn't seem to be copied.  I think the build.gradle is not correct

**Comment by lental** [comment]
love it. thanks!

**Pull request merged**
