### PR TITLE
Pba 3151

### PR DESCRIPTION
**Pull request by bindumadhav**
Refactored Automation Hook

### CODE REVIEW

**Comment by lental** [comment]
these may have to wait until we update the 'dev' branch with updated SDKs

these apps will not be able to build without the updated SDKs

**Comment by bindumadhav** [comment]
sure

**Comment by lental** [comment]
I have updated the sdks on dev branch. can you merge the dev branch into this one, and confirm the loggers work?

**Comment by bindumadhav** [comment]
Sure , will test the logger with updated sdks and get back

**Comment by bindumadhav** [comment]
Merged the dev branch of sample apps into PBA-3151 branch of sample app .

Tested the automation hook , it works fine .

**Pull request merged**
