### PR TITLE
[PLAYER-2841] Android Heartbeat to SSAI

### PR DESCRIPTION
**Pull request by orobles-ooyala**
- Due to freezing issues on MediaPlayer, move to
  ExoPlayer

### CODE REVIEW

**Review by brol1dev — APPROVED** [review]
LGTM

**Review by ipadilla4 — APPROVED** [review]
LGTM

**Comment by orobles-ooyala** [comment]
@rcvrgs @pilievOoyala @akshaydch11 can we merge this?

**Review by cacel — APPROVED** [review]

**Comment by brol1dev** [comment]
I'm merging this PR. Thanks guys! 👍

**Pull request merged**
