### PR TITLE
OptionsSampleAppAutomationHook

### PR DESCRIPTION
**Pull request by bindumadhav**
Automation Hook for Options Sample App

### CODE REVIEW

**Comment by jonslenkooyala** [comment]
Looks like something happened with the formatting? Please run it through Xcode's automatic code formatting for indentation?

**Comment by lental** [comment]
bump @bindumadhav , there seems to be tabbing issues.  can you look  nto this before we merge?

**Comment by bindumadhav** [comment]
yes , i will look into it .

On Mon, Apr 25, 2016 at 5:47 PM, lental notifications@github.com wrote:

> bump @bindumadhav https://github.com/bindumadhav , there seems to be
> tabbing issues. can you look nto this before we merge?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/ooyala/android-sample-apps/pull/94#issuecomment-214574351

## 

Regards,

BinduMadhav Sondur
310, Crescent Village Circle , #2110 ,
San Jose , CA - 95134

PH: 315-247-5338

**Comment by lental** [comment]
@bindumadhav bump on this PR

**Comment by bindumadhav** [comment]
oops , got sidetracked , will take a look at this soon .

**Comment by Matthew-C** [comment]
is this pull request still valid? If not can we close this for now?

**Comment by bindumadhav** [comment]
this pull request is now invalid because the other branch has been merged , will close this PR

**Pull request closed without merging**
