### PR TITLE
Two new activities for NPAW-FW and NPAW-IMA

### PR DESCRIPTION
**Pull request by ramanamca04**
@akshaydch11  @rcvrgs  

As requested by @pkumar, There are two new activities created for NPAW integration of FW and IMA. Please review the code changes and merge them into Candidate branch. Thanks for your time.

### CODE REVIEW

**Review by akshaydch11 — APPROVED** [review]

**Comment by akshaydch11** [comment]
LGTM

**Comment by ramanamca04** [comment]
@DmitriiMaslov Changed the base branch to Dev. Could you please get it reviewed the PR and merge into dev soon?

**Review by SergeyBicarte — CHANGES_REQUESTED** [review]
Pls update Title of PR with JIRA number ticket for that task, make branch with these changes named like JIRA ticket name (number) ( for example PLAYER-1234 or PBA-1234 or whatever it named in JIRA) and make PR from that branch in dev

**Comment by ramanamca04** [comment]
@DmitriiMaslov fya

**Pull request closed without merging**
