### PR TITLE
[PLAYER-4146] Showcase using Ooyala Pulse and DFP with SSAI

### PR DESCRIPTION
**Pull request by orobles-ooyala**

### CODE REVIEW

**Comment by cacel** [comment]
@orobles-ooyala It looks ssaiPlayerParams.json and ooyalaPulsePlayerParams.json are the same files. Maybe you can modify one of them to show how position or cuePoints works.

LGTM after modify one of the files.

**Comment by orobles-ooyala** [comment]
Changed both, position and cue points.

**Review by cacel — APPROVED** [review]
LGTM

**Review by ipadilla4 — APPROVED** [review]
LGTM

**Comment by pilievOoyala** [comment]
LGTM

**Comment by pilievOoyala** [comment]
@rcvrgs @akshaydch11  can you review too?

**Review by brol1dev — APPROVED** [review]
LGTM

**Pull request merged**
