### PR TITLE
PBA-5408

### PR DESCRIPTION
**Pull request by AlinaVoronkovaEpam**
Full screen player implementation with Recycler View.

### CODE REVIEW

**Comment by IvanSakharovskii** [comment]
Pull Request Approved (EPAM Team). Please add this account in team for including me in reviewers

**Comment by AlinaVoronkovaEpam** [comment]
I would like to mention that after moving to a full screen mode, the Player has some visible delays (I mean that a scrubber bar is moving but video isn't playing for a couple of seconds).

**Comment by brol1dev** [comment]
Looks great! I'm going to ask you to add some of these code as part of our SDK, it will be helpful for customers to use some of it, for example, `FullscreenHelper` since that is the one managing the in and out of fullscreen mode.

Let's talk about it later on.

**Comment by AlinaVoronkovaEpam** [comment]
I totally agree with you, it's a good idea, and I also thought about moving the helper to the SDK.
By the way, could you tell me the concrete place, if it's possibly, where I should add this helper. Because as I understand you have some ideas.

**Comment by akshaydch11** [comment]
@AlinaVoronkovaEpam You can add FullScreenHelper inside SKIN SDK which can be found here : https://github.com/ooyala/native-skin/tree/stable/sdk/android/skin
Also, once you add that could you please update this PR removing class from here and making other necessary changes in this code.

**Comment by brol1dev** [comment]
I'm going to merge this PR for the moment, when we make the new release we will include `FullscreenHelper` as part of the SkinSDK and we can update this sample app with the `FullscreenHelper` of the SkinSDK.

**Review by brol1dev — APPROVED** [review]

**Pull request merged**
